name: bostonprices

on:
  create:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
      
      
    - name: Docker Login

      uses: docker/login-action@v2.1.0
      with:

        username: ${{ secrets.DOCKERHUB_USERNAME }}

        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
        push: true
        tags: index.docker.io/kavehcosing/bostonprices:${{ github.sha }}
        file: ./Dockerfile
        
        
        
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2.2.5
      with:
    # Name of the Azure Web App
        app-name: ds20m013-iris-app
    # Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets
        publish-profile: ${{ secrets.PUBLISH_PROFILE_AZURE }}
  
        images: index.docker.io/kavehcoding/bostonprices:${{ github.sha }}